/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.5.2-Docker-4.0.0 (4.5)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"

	"gopkg.in/validator.v2"
)

// PluginsNetboxTopologyViewsCoordinateGroupsCreateRequest - struct for PluginsNetboxTopologyViewsCoordinateGroupsCreateRequest
type PluginsNetboxTopologyViewsCoordinateGroupsCreateRequest struct {
	CoordinateGroupRequest        *CoordinateGroupRequest
	ArrayOfCoordinateGroupRequest *[]CoordinateGroupRequest
}

// CoordinateGroupRequestAsPluginsNetboxTopologyViewsCoordinateGroupsCreateRequest is a convenience function that returns CoordinateGroupRequest wrapped in PluginsNetboxTopologyViewsCoordinateGroupsCreateRequest
func CoordinateGroupRequestAsPluginsNetboxTopologyViewsCoordinateGroupsCreateRequest(v *CoordinateGroupRequest) PluginsNetboxTopologyViewsCoordinateGroupsCreateRequest {
	return PluginsNetboxTopologyViewsCoordinateGroupsCreateRequest{
		CoordinateGroupRequest: v,
	}
}

// []CoordinateGroupRequestAsPluginsNetboxTopologyViewsCoordinateGroupsCreateRequest is a convenience function that returns []CoordinateGroupRequest wrapped in PluginsNetboxTopologyViewsCoordinateGroupsCreateRequest
func ArrayOfCoordinateGroupRequestAsPluginsNetboxTopologyViewsCoordinateGroupsCreateRequest(v *[]CoordinateGroupRequest) PluginsNetboxTopologyViewsCoordinateGroupsCreateRequest {
	return PluginsNetboxTopologyViewsCoordinateGroupsCreateRequest{
		ArrayOfCoordinateGroupRequest: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *PluginsNetboxTopologyViewsCoordinateGroupsCreateRequest) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into CoordinateGroupRequest
	err = newStrictDecoder(data).Decode(&dst.CoordinateGroupRequest)
	if err == nil {
		jsonCoordinateGroupRequest, _ := json.Marshal(dst.CoordinateGroupRequest)
		if string(jsonCoordinateGroupRequest) == "{}" { // empty struct
			dst.CoordinateGroupRequest = nil
		} else {
			if err = validator.Validate(dst.CoordinateGroupRequest); err != nil {
				dst.CoordinateGroupRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.CoordinateGroupRequest = nil
	}

	// try to unmarshal data into ArrayOfCoordinateGroupRequest
	err = newStrictDecoder(data).Decode(&dst.ArrayOfCoordinateGroupRequest)
	if err == nil {
		jsonArrayOfCoordinateGroupRequest, _ := json.Marshal(dst.ArrayOfCoordinateGroupRequest)
		if string(jsonArrayOfCoordinateGroupRequest) == "{}" { // empty struct
			dst.ArrayOfCoordinateGroupRequest = nil
		} else {
			if err = validator.Validate(dst.ArrayOfCoordinateGroupRequest); err != nil {
				dst.ArrayOfCoordinateGroupRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.ArrayOfCoordinateGroupRequest = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.CoordinateGroupRequest = nil
		dst.ArrayOfCoordinateGroupRequest = nil

		return fmt.Errorf("data matches more than one schema in oneOf(PluginsNetboxTopologyViewsCoordinateGroupsCreateRequest)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(PluginsNetboxTopologyViewsCoordinateGroupsCreateRequest)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PluginsNetboxTopologyViewsCoordinateGroupsCreateRequest) MarshalJSON() ([]byte, error) {
	if src.CoordinateGroupRequest != nil {
		return json.Marshal(&src.CoordinateGroupRequest)
	}

	if src.ArrayOfCoordinateGroupRequest != nil {
		return json.Marshal(&src.ArrayOfCoordinateGroupRequest)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PluginsNetboxTopologyViewsCoordinateGroupsCreateRequest) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.CoordinateGroupRequest != nil {
		return obj.CoordinateGroupRequest
	}

	if obj.ArrayOfCoordinateGroupRequest != nil {
		return obj.ArrayOfCoordinateGroupRequest
	}

	// all schemas are nil
	return nil
}

type NullablePluginsNetboxTopologyViewsCoordinateGroupsCreateRequest struct {
	value *PluginsNetboxTopologyViewsCoordinateGroupsCreateRequest
	isSet bool
}

func (v NullablePluginsNetboxTopologyViewsCoordinateGroupsCreateRequest) Get() *PluginsNetboxTopologyViewsCoordinateGroupsCreateRequest {
	return v.value
}

func (v *NullablePluginsNetboxTopologyViewsCoordinateGroupsCreateRequest) Set(val *PluginsNetboxTopologyViewsCoordinateGroupsCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePluginsNetboxTopologyViewsCoordinateGroupsCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePluginsNetboxTopologyViewsCoordinateGroupsCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePluginsNetboxTopologyViewsCoordinateGroupsCreateRequest(val *PluginsNetboxTopologyViewsCoordinateGroupsCreateRequest) *NullablePluginsNetboxTopologyViewsCoordinateGroupsCreateRequest {
	return &NullablePluginsNetboxTopologyViewsCoordinateGroupsCreateRequest{value: val, isSet: true}
}

func (v NullablePluginsNetboxTopologyViewsCoordinateGroupsCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePluginsNetboxTopologyViewsCoordinateGroupsCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
