/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.5.2-Docker-4.0.0 (4.5)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"

	"gopkg.in/validator.v2"
)

// PluginsNetboxTopologyViewsCircuitcoordinateCreateRequest - struct for PluginsNetboxTopologyViewsCircuitcoordinateCreateRequest
type PluginsNetboxTopologyViewsCircuitcoordinateCreateRequest struct {
	CircuitCoordinateRequest        *CircuitCoordinateRequest
	ArrayOfCircuitCoordinateRequest *[]CircuitCoordinateRequest
}

// CircuitCoordinateRequestAsPluginsNetboxTopologyViewsCircuitcoordinateCreateRequest is a convenience function that returns CircuitCoordinateRequest wrapped in PluginsNetboxTopologyViewsCircuitcoordinateCreateRequest
func CircuitCoordinateRequestAsPluginsNetboxTopologyViewsCircuitcoordinateCreateRequest(v *CircuitCoordinateRequest) PluginsNetboxTopologyViewsCircuitcoordinateCreateRequest {
	return PluginsNetboxTopologyViewsCircuitcoordinateCreateRequest{
		CircuitCoordinateRequest: v,
	}
}

// []CircuitCoordinateRequestAsPluginsNetboxTopologyViewsCircuitcoordinateCreateRequest is a convenience function that returns []CircuitCoordinateRequest wrapped in PluginsNetboxTopologyViewsCircuitcoordinateCreateRequest
func ArrayOfCircuitCoordinateRequestAsPluginsNetboxTopologyViewsCircuitcoordinateCreateRequest(v *[]CircuitCoordinateRequest) PluginsNetboxTopologyViewsCircuitcoordinateCreateRequest {
	return PluginsNetboxTopologyViewsCircuitcoordinateCreateRequest{
		ArrayOfCircuitCoordinateRequest: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *PluginsNetboxTopologyViewsCircuitcoordinateCreateRequest) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into CircuitCoordinateRequest
	err = newStrictDecoder(data).Decode(&dst.CircuitCoordinateRequest)
	if err == nil {
		jsonCircuitCoordinateRequest, _ := json.Marshal(dst.CircuitCoordinateRequest)
		if string(jsonCircuitCoordinateRequest) == "{}" { // empty struct
			dst.CircuitCoordinateRequest = nil
		} else {
			if err = validator.Validate(dst.CircuitCoordinateRequest); err != nil {
				dst.CircuitCoordinateRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.CircuitCoordinateRequest = nil
	}

	// try to unmarshal data into ArrayOfCircuitCoordinateRequest
	err = newStrictDecoder(data).Decode(&dst.ArrayOfCircuitCoordinateRequest)
	if err == nil {
		jsonArrayOfCircuitCoordinateRequest, _ := json.Marshal(dst.ArrayOfCircuitCoordinateRequest)
		if string(jsonArrayOfCircuitCoordinateRequest) == "{}" { // empty struct
			dst.ArrayOfCircuitCoordinateRequest = nil
		} else {
			if err = validator.Validate(dst.ArrayOfCircuitCoordinateRequest); err != nil {
				dst.ArrayOfCircuitCoordinateRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.ArrayOfCircuitCoordinateRequest = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.CircuitCoordinateRequest = nil
		dst.ArrayOfCircuitCoordinateRequest = nil

		return fmt.Errorf("data matches more than one schema in oneOf(PluginsNetboxTopologyViewsCircuitcoordinateCreateRequest)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(PluginsNetboxTopologyViewsCircuitcoordinateCreateRequest)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PluginsNetboxTopologyViewsCircuitcoordinateCreateRequest) MarshalJSON() ([]byte, error) {
	if src.CircuitCoordinateRequest != nil {
		return json.Marshal(&src.CircuitCoordinateRequest)
	}

	if src.ArrayOfCircuitCoordinateRequest != nil {
		return json.Marshal(&src.ArrayOfCircuitCoordinateRequest)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PluginsNetboxTopologyViewsCircuitcoordinateCreateRequest) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.CircuitCoordinateRequest != nil {
		return obj.CircuitCoordinateRequest
	}

	if obj.ArrayOfCircuitCoordinateRequest != nil {
		return obj.ArrayOfCircuitCoordinateRequest
	}

	// all schemas are nil
	return nil
}

type NullablePluginsNetboxTopologyViewsCircuitcoordinateCreateRequest struct {
	value *PluginsNetboxTopologyViewsCircuitcoordinateCreateRequest
	isSet bool
}

func (v NullablePluginsNetboxTopologyViewsCircuitcoordinateCreateRequest) Get() *PluginsNetboxTopologyViewsCircuitcoordinateCreateRequest {
	return v.value
}

func (v *NullablePluginsNetboxTopologyViewsCircuitcoordinateCreateRequest) Set(val *PluginsNetboxTopologyViewsCircuitcoordinateCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePluginsNetboxTopologyViewsCircuitcoordinateCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePluginsNetboxTopologyViewsCircuitcoordinateCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePluginsNetboxTopologyViewsCircuitcoordinateCreateRequest(val *PluginsNetboxTopologyViewsCircuitcoordinateCreateRequest) *NullablePluginsNetboxTopologyViewsCircuitcoordinateCreateRequest {
	return &NullablePluginsNetboxTopologyViewsCircuitcoordinateCreateRequest{value: val, isSet: true}
}

func (v NullablePluginsNetboxTopologyViewsCircuitcoordinateCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePluginsNetboxTopologyViewsCircuitcoordinateCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
