/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.5.2-Docker-4.0.0 (4.5)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"

	"gopkg.in/validator.v2"
)

// PluginsNetboxTopologyViewsCoordinateCreateRequest - struct for PluginsNetboxTopologyViewsCoordinateCreateRequest
type PluginsNetboxTopologyViewsCoordinateCreateRequest struct {
	CoordinateRequest        *CoordinateRequest
	ArrayOfCoordinateRequest *[]CoordinateRequest
}

// CoordinateRequestAsPluginsNetboxTopologyViewsCoordinateCreateRequest is a convenience function that returns CoordinateRequest wrapped in PluginsNetboxTopologyViewsCoordinateCreateRequest
func CoordinateRequestAsPluginsNetboxTopologyViewsCoordinateCreateRequest(v *CoordinateRequest) PluginsNetboxTopologyViewsCoordinateCreateRequest {
	return PluginsNetboxTopologyViewsCoordinateCreateRequest{
		CoordinateRequest: v,
	}
}

// []CoordinateRequestAsPluginsNetboxTopologyViewsCoordinateCreateRequest is a convenience function that returns []CoordinateRequest wrapped in PluginsNetboxTopologyViewsCoordinateCreateRequest
func ArrayOfCoordinateRequestAsPluginsNetboxTopologyViewsCoordinateCreateRequest(v *[]CoordinateRequest) PluginsNetboxTopologyViewsCoordinateCreateRequest {
	return PluginsNetboxTopologyViewsCoordinateCreateRequest{
		ArrayOfCoordinateRequest: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *PluginsNetboxTopologyViewsCoordinateCreateRequest) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into CoordinateRequest
	err = newStrictDecoder(data).Decode(&dst.CoordinateRequest)
	if err == nil {
		jsonCoordinateRequest, _ := json.Marshal(dst.CoordinateRequest)
		if string(jsonCoordinateRequest) == "{}" { // empty struct
			dst.CoordinateRequest = nil
		} else {
			if err = validator.Validate(dst.CoordinateRequest); err != nil {
				dst.CoordinateRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.CoordinateRequest = nil
	}

	// try to unmarshal data into ArrayOfCoordinateRequest
	err = newStrictDecoder(data).Decode(&dst.ArrayOfCoordinateRequest)
	if err == nil {
		jsonArrayOfCoordinateRequest, _ := json.Marshal(dst.ArrayOfCoordinateRequest)
		if string(jsonArrayOfCoordinateRequest) == "{}" { // empty struct
			dst.ArrayOfCoordinateRequest = nil
		} else {
			if err = validator.Validate(dst.ArrayOfCoordinateRequest); err != nil {
				dst.ArrayOfCoordinateRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.ArrayOfCoordinateRequest = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.CoordinateRequest = nil
		dst.ArrayOfCoordinateRequest = nil

		return fmt.Errorf("data matches more than one schema in oneOf(PluginsNetboxTopologyViewsCoordinateCreateRequest)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(PluginsNetboxTopologyViewsCoordinateCreateRequest)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PluginsNetboxTopologyViewsCoordinateCreateRequest) MarshalJSON() ([]byte, error) {
	if src.CoordinateRequest != nil {
		return json.Marshal(&src.CoordinateRequest)
	}

	if src.ArrayOfCoordinateRequest != nil {
		return json.Marshal(&src.ArrayOfCoordinateRequest)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PluginsNetboxTopologyViewsCoordinateCreateRequest) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.CoordinateRequest != nil {
		return obj.CoordinateRequest
	}

	if obj.ArrayOfCoordinateRequest != nil {
		return obj.ArrayOfCoordinateRequest
	}

	// all schemas are nil
	return nil
}

type NullablePluginsNetboxTopologyViewsCoordinateCreateRequest struct {
	value *PluginsNetboxTopologyViewsCoordinateCreateRequest
	isSet bool
}

func (v NullablePluginsNetboxTopologyViewsCoordinateCreateRequest) Get() *PluginsNetboxTopologyViewsCoordinateCreateRequest {
	return v.value
}

func (v *NullablePluginsNetboxTopologyViewsCoordinateCreateRequest) Set(val *PluginsNetboxTopologyViewsCoordinateCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePluginsNetboxTopologyViewsCoordinateCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePluginsNetboxTopologyViewsCoordinateCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePluginsNetboxTopologyViewsCoordinateCreateRequest(val *PluginsNetboxTopologyViewsCoordinateCreateRequest) *NullablePluginsNetboxTopologyViewsCoordinateCreateRequest {
	return &NullablePluginsNetboxTopologyViewsCoordinateCreateRequest{value: val, isSet: true}
}

func (v NullablePluginsNetboxTopologyViewsCoordinateCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePluginsNetboxTopologyViewsCoordinateCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
