/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.4.5-Docker-3.4.1 (4.4)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
)

// checks if the PatchedPowerPanelCoordinateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchedPowerPanelCoordinateRequest{}

// PatchedPowerPanelCoordinateRequest Adds support for custom fields and tags.
type PatchedPowerPanelCoordinateRequest struct {
	// X-coordinate of the device (horizontal) on the canvas. Smaller values correspond to a position further to the left on the monitor.
	X *int32 `json:"x,omitempty"`
	// Y-coordinate of the device (vertical) on the canvas. Smaller values correspond to a position further up on the monitor.
	Y                    *int32 `json:"y,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PatchedPowerPanelCoordinateRequest PatchedPowerPanelCoordinateRequest

// NewPatchedPowerPanelCoordinateRequest instantiates a new PatchedPowerPanelCoordinateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchedPowerPanelCoordinateRequest() *PatchedPowerPanelCoordinateRequest {
	this := PatchedPowerPanelCoordinateRequest{}
	return &this
}

// NewPatchedPowerPanelCoordinateRequestWithDefaults instantiates a new PatchedPowerPanelCoordinateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchedPowerPanelCoordinateRequestWithDefaults() *PatchedPowerPanelCoordinateRequest {
	this := PatchedPowerPanelCoordinateRequest{}
	return &this
}

// GetX returns the X field value if set, zero value otherwise.
func (o *PatchedPowerPanelCoordinateRequest) GetX() int32 {
	if o == nil || IsNil(o.X) {
		var ret int32
		return ret
	}
	return *o.X
}

// GetXOk returns a tuple with the X field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedPowerPanelCoordinateRequest) GetXOk() (*int32, bool) {
	if o == nil || IsNil(o.X) {
		return nil, false
	}
	return o.X, true
}

// HasX returns a boolean if a field has been set.
func (o *PatchedPowerPanelCoordinateRequest) HasX() bool {
	if o != nil && !IsNil(o.X) {
		return true
	}

	return false
}

// SetX gets a reference to the given int32 and assigns it to the X field.
func (o *PatchedPowerPanelCoordinateRequest) SetX(v int32) {
	o.X = &v
}

// GetY returns the Y field value if set, zero value otherwise.
func (o *PatchedPowerPanelCoordinateRequest) GetY() int32 {
	if o == nil || IsNil(o.Y) {
		var ret int32
		return ret
	}
	return *o.Y
}

// GetYOk returns a tuple with the Y field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedPowerPanelCoordinateRequest) GetYOk() (*int32, bool) {
	if o == nil || IsNil(o.Y) {
		return nil, false
	}
	return o.Y, true
}

// HasY returns a boolean if a field has been set.
func (o *PatchedPowerPanelCoordinateRequest) HasY() bool {
	if o != nil && !IsNil(o.Y) {
		return true
	}

	return false
}

// SetY gets a reference to the given int32 and assigns it to the Y field.
func (o *PatchedPowerPanelCoordinateRequest) SetY(v int32) {
	o.Y = &v
}

func (o PatchedPowerPanelCoordinateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchedPowerPanelCoordinateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.X) {
		toSerialize["x"] = o.X
	}
	if !IsNil(o.Y) {
		toSerialize["y"] = o.Y
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PatchedPowerPanelCoordinateRequest) UnmarshalJSON(data []byte) (err error) {
	varPatchedPowerPanelCoordinateRequest := _PatchedPowerPanelCoordinateRequest{}

	err = json.Unmarshal(data, &varPatchedPowerPanelCoordinateRequest)

	if err != nil {
		return err
	}

	*o = PatchedPowerPanelCoordinateRequest(varPatchedPowerPanelCoordinateRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "x")
		delete(additionalProperties, "y")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePatchedPowerPanelCoordinateRequest struct {
	value *PatchedPowerPanelCoordinateRequest
	isSet bool
}

func (v NullablePatchedPowerPanelCoordinateRequest) Get() *PatchedPowerPanelCoordinateRequest {
	return v.value
}

func (v *NullablePatchedPowerPanelCoordinateRequest) Set(val *PatchedPowerPanelCoordinateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedPowerPanelCoordinateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedPowerPanelCoordinateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedPowerPanelCoordinateRequest(val *PatchedPowerPanelCoordinateRequest) *NullablePatchedPowerPanelCoordinateRequest {
	return &NullablePatchedPowerPanelCoordinateRequest{value: val, isSet: true}
}

func (v NullablePatchedPowerPanelCoordinateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedPowerPanelCoordinateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
