/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.5.2-Docker-4.0.0 (4.5)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"

	"gopkg.in/validator.v2"
)

// PluginsNetboxTopologyViewsPowerpanelcoordinateCreateRequest - struct for PluginsNetboxTopologyViewsPowerpanelcoordinateCreateRequest
type PluginsNetboxTopologyViewsPowerpanelcoordinateCreateRequest struct {
	PowerPanelCoordinateRequest        *PowerPanelCoordinateRequest
	ArrayOfPowerPanelCoordinateRequest *[]PowerPanelCoordinateRequest
}

// PowerPanelCoordinateRequestAsPluginsNetboxTopologyViewsPowerpanelcoordinateCreateRequest is a convenience function that returns PowerPanelCoordinateRequest wrapped in PluginsNetboxTopologyViewsPowerpanelcoordinateCreateRequest
func PowerPanelCoordinateRequestAsPluginsNetboxTopologyViewsPowerpanelcoordinateCreateRequest(v *PowerPanelCoordinateRequest) PluginsNetboxTopologyViewsPowerpanelcoordinateCreateRequest {
	return PluginsNetboxTopologyViewsPowerpanelcoordinateCreateRequest{
		PowerPanelCoordinateRequest: v,
	}
}

// []PowerPanelCoordinateRequestAsPluginsNetboxTopologyViewsPowerpanelcoordinateCreateRequest is a convenience function that returns []PowerPanelCoordinateRequest wrapped in PluginsNetboxTopologyViewsPowerpanelcoordinateCreateRequest
func ArrayOfPowerPanelCoordinateRequestAsPluginsNetboxTopologyViewsPowerpanelcoordinateCreateRequest(v *[]PowerPanelCoordinateRequest) PluginsNetboxTopologyViewsPowerpanelcoordinateCreateRequest {
	return PluginsNetboxTopologyViewsPowerpanelcoordinateCreateRequest{
		ArrayOfPowerPanelCoordinateRequest: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *PluginsNetboxTopologyViewsPowerpanelcoordinateCreateRequest) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into PowerPanelCoordinateRequest
	err = newStrictDecoder(data).Decode(&dst.PowerPanelCoordinateRequest)
	if err == nil {
		jsonPowerPanelCoordinateRequest, _ := json.Marshal(dst.PowerPanelCoordinateRequest)
		if string(jsonPowerPanelCoordinateRequest) == "{}" { // empty struct
			dst.PowerPanelCoordinateRequest = nil
		} else {
			if err = validator.Validate(dst.PowerPanelCoordinateRequest); err != nil {
				dst.PowerPanelCoordinateRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.PowerPanelCoordinateRequest = nil
	}

	// try to unmarshal data into ArrayOfPowerPanelCoordinateRequest
	err = newStrictDecoder(data).Decode(&dst.ArrayOfPowerPanelCoordinateRequest)
	if err == nil {
		jsonArrayOfPowerPanelCoordinateRequest, _ := json.Marshal(dst.ArrayOfPowerPanelCoordinateRequest)
		if string(jsonArrayOfPowerPanelCoordinateRequest) == "{}" { // empty struct
			dst.ArrayOfPowerPanelCoordinateRequest = nil
		} else {
			if err = validator.Validate(dst.ArrayOfPowerPanelCoordinateRequest); err != nil {
				dst.ArrayOfPowerPanelCoordinateRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.ArrayOfPowerPanelCoordinateRequest = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.PowerPanelCoordinateRequest = nil
		dst.ArrayOfPowerPanelCoordinateRequest = nil

		return fmt.Errorf("data matches more than one schema in oneOf(PluginsNetboxTopologyViewsPowerpanelcoordinateCreateRequest)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(PluginsNetboxTopologyViewsPowerpanelcoordinateCreateRequest)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PluginsNetboxTopologyViewsPowerpanelcoordinateCreateRequest) MarshalJSON() ([]byte, error) {
	if src.PowerPanelCoordinateRequest != nil {
		return json.Marshal(&src.PowerPanelCoordinateRequest)
	}

	if src.ArrayOfPowerPanelCoordinateRequest != nil {
		return json.Marshal(&src.ArrayOfPowerPanelCoordinateRequest)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PluginsNetboxTopologyViewsPowerpanelcoordinateCreateRequest) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.PowerPanelCoordinateRequest != nil {
		return obj.PowerPanelCoordinateRequest
	}

	if obj.ArrayOfPowerPanelCoordinateRequest != nil {
		return obj.ArrayOfPowerPanelCoordinateRequest
	}

	// all schemas are nil
	return nil
}

type NullablePluginsNetboxTopologyViewsPowerpanelcoordinateCreateRequest struct {
	value *PluginsNetboxTopologyViewsPowerpanelcoordinateCreateRequest
	isSet bool
}

func (v NullablePluginsNetboxTopologyViewsPowerpanelcoordinateCreateRequest) Get() *PluginsNetboxTopologyViewsPowerpanelcoordinateCreateRequest {
	return v.value
}

func (v *NullablePluginsNetboxTopologyViewsPowerpanelcoordinateCreateRequest) Set(val *PluginsNetboxTopologyViewsPowerpanelcoordinateCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePluginsNetboxTopologyViewsPowerpanelcoordinateCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePluginsNetboxTopologyViewsPowerpanelcoordinateCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePluginsNetboxTopologyViewsPowerpanelcoordinateCreateRequest(val *PluginsNetboxTopologyViewsPowerpanelcoordinateCreateRequest) *NullablePluginsNetboxTopologyViewsPowerpanelcoordinateCreateRequest {
	return &NullablePluginsNetboxTopologyViewsPowerpanelcoordinateCreateRequest{value: val, isSet: true}
}

func (v NullablePluginsNetboxTopologyViewsPowerpanelcoordinateCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePluginsNetboxTopologyViewsPowerpanelcoordinateCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
