/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.5.2-Docker-4.0.0 (4.5)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"

	"gopkg.in/validator.v2"
)

// PluginsNetboxTopologyViewsPowerfeedcoordinateCreateRequest - struct for PluginsNetboxTopologyViewsPowerfeedcoordinateCreateRequest
type PluginsNetboxTopologyViewsPowerfeedcoordinateCreateRequest struct {
	PowerFeedCoordinateRequest        *PowerFeedCoordinateRequest
	ArrayOfPowerFeedCoordinateRequest *[]PowerFeedCoordinateRequest
}

// PowerFeedCoordinateRequestAsPluginsNetboxTopologyViewsPowerfeedcoordinateCreateRequest is a convenience function that returns PowerFeedCoordinateRequest wrapped in PluginsNetboxTopologyViewsPowerfeedcoordinateCreateRequest
func PowerFeedCoordinateRequestAsPluginsNetboxTopologyViewsPowerfeedcoordinateCreateRequest(v *PowerFeedCoordinateRequest) PluginsNetboxTopologyViewsPowerfeedcoordinateCreateRequest {
	return PluginsNetboxTopologyViewsPowerfeedcoordinateCreateRequest{
		PowerFeedCoordinateRequest: v,
	}
}

// []PowerFeedCoordinateRequestAsPluginsNetboxTopologyViewsPowerfeedcoordinateCreateRequest is a convenience function that returns []PowerFeedCoordinateRequest wrapped in PluginsNetboxTopologyViewsPowerfeedcoordinateCreateRequest
func ArrayOfPowerFeedCoordinateRequestAsPluginsNetboxTopologyViewsPowerfeedcoordinateCreateRequest(v *[]PowerFeedCoordinateRequest) PluginsNetboxTopologyViewsPowerfeedcoordinateCreateRequest {
	return PluginsNetboxTopologyViewsPowerfeedcoordinateCreateRequest{
		ArrayOfPowerFeedCoordinateRequest: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *PluginsNetboxTopologyViewsPowerfeedcoordinateCreateRequest) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into PowerFeedCoordinateRequest
	err = newStrictDecoder(data).Decode(&dst.PowerFeedCoordinateRequest)
	if err == nil {
		jsonPowerFeedCoordinateRequest, _ := json.Marshal(dst.PowerFeedCoordinateRequest)
		if string(jsonPowerFeedCoordinateRequest) == "{}" { // empty struct
			dst.PowerFeedCoordinateRequest = nil
		} else {
			if err = validator.Validate(dst.PowerFeedCoordinateRequest); err != nil {
				dst.PowerFeedCoordinateRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.PowerFeedCoordinateRequest = nil
	}

	// try to unmarshal data into ArrayOfPowerFeedCoordinateRequest
	err = newStrictDecoder(data).Decode(&dst.ArrayOfPowerFeedCoordinateRequest)
	if err == nil {
		jsonArrayOfPowerFeedCoordinateRequest, _ := json.Marshal(dst.ArrayOfPowerFeedCoordinateRequest)
		if string(jsonArrayOfPowerFeedCoordinateRequest) == "{}" { // empty struct
			dst.ArrayOfPowerFeedCoordinateRequest = nil
		} else {
			if err = validator.Validate(dst.ArrayOfPowerFeedCoordinateRequest); err != nil {
				dst.ArrayOfPowerFeedCoordinateRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.ArrayOfPowerFeedCoordinateRequest = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.PowerFeedCoordinateRequest = nil
		dst.ArrayOfPowerFeedCoordinateRequest = nil

		return fmt.Errorf("data matches more than one schema in oneOf(PluginsNetboxTopologyViewsPowerfeedcoordinateCreateRequest)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(PluginsNetboxTopologyViewsPowerfeedcoordinateCreateRequest)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PluginsNetboxTopologyViewsPowerfeedcoordinateCreateRequest) MarshalJSON() ([]byte, error) {
	if src.PowerFeedCoordinateRequest != nil {
		return json.Marshal(&src.PowerFeedCoordinateRequest)
	}

	if src.ArrayOfPowerFeedCoordinateRequest != nil {
		return json.Marshal(&src.ArrayOfPowerFeedCoordinateRequest)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PluginsNetboxTopologyViewsPowerfeedcoordinateCreateRequest) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.PowerFeedCoordinateRequest != nil {
		return obj.PowerFeedCoordinateRequest
	}

	if obj.ArrayOfPowerFeedCoordinateRequest != nil {
		return obj.ArrayOfPowerFeedCoordinateRequest
	}

	// all schemas are nil
	return nil
}

type NullablePluginsNetboxTopologyViewsPowerfeedcoordinateCreateRequest struct {
	value *PluginsNetboxTopologyViewsPowerfeedcoordinateCreateRequest
	isSet bool
}

func (v NullablePluginsNetboxTopologyViewsPowerfeedcoordinateCreateRequest) Get() *PluginsNetboxTopologyViewsPowerfeedcoordinateCreateRequest {
	return v.value
}

func (v *NullablePluginsNetboxTopologyViewsPowerfeedcoordinateCreateRequest) Set(val *PluginsNetboxTopologyViewsPowerfeedcoordinateCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePluginsNetboxTopologyViewsPowerfeedcoordinateCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePluginsNetboxTopologyViewsPowerfeedcoordinateCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePluginsNetboxTopologyViewsPowerfeedcoordinateCreateRequest(val *PluginsNetboxTopologyViewsPowerfeedcoordinateCreateRequest) *NullablePluginsNetboxTopologyViewsPowerfeedcoordinateCreateRequest {
	return &NullablePluginsNetboxTopologyViewsPowerfeedcoordinateCreateRequest{value: val, isSet: true}
}

func (v NullablePluginsNetboxTopologyViewsPowerfeedcoordinateCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePluginsNetboxTopologyViewsPowerfeedcoordinateCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
