/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.5.2-Docker-4.0.0 (4.5)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// checks if the PowerPanelCoordinateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PowerPanelCoordinateRequest{}

// PowerPanelCoordinateRequest Adds support for custom fields and tags.
type PowerPanelCoordinateRequest struct {
	// X-coordinate of the device (horizontal) on the canvas. Smaller values correspond to a position further to the left on the monitor.
	X int32 `json:"x"`
	// Y-coordinate of the device (vertical) on the canvas. Smaller values correspond to a position further up on the monitor.
	Y                    int32 `json:"y"`
	AdditionalProperties map[string]interface{}
}

type _PowerPanelCoordinateRequest PowerPanelCoordinateRequest

// NewPowerPanelCoordinateRequest instantiates a new PowerPanelCoordinateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPowerPanelCoordinateRequest(x int32, y int32) *PowerPanelCoordinateRequest {
	this := PowerPanelCoordinateRequest{}
	this.X = x
	this.Y = y
	return &this
}

// NewPowerPanelCoordinateRequestWithDefaults instantiates a new PowerPanelCoordinateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPowerPanelCoordinateRequestWithDefaults() *PowerPanelCoordinateRequest {
	this := PowerPanelCoordinateRequest{}
	return &this
}

// GetX returns the X field value
func (o *PowerPanelCoordinateRequest) GetX() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.X
}

// GetXOk returns a tuple with the X field value
// and a boolean to check if the value has been set.
func (o *PowerPanelCoordinateRequest) GetXOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.X, true
}

// SetX sets field value
func (o *PowerPanelCoordinateRequest) SetX(v int32) {
	o.X = v
}

// GetY returns the Y field value
func (o *PowerPanelCoordinateRequest) GetY() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Y
}

// GetYOk returns a tuple with the Y field value
// and a boolean to check if the value has been set.
func (o *PowerPanelCoordinateRequest) GetYOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Y, true
}

// SetY sets field value
func (o *PowerPanelCoordinateRequest) SetY(v int32) {
	o.Y = v
}

func (o PowerPanelCoordinateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PowerPanelCoordinateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["x"] = o.X
	toSerialize["y"] = o.Y

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PowerPanelCoordinateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"x",
		"y",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	varPowerPanelCoordinateRequest := _PowerPanelCoordinateRequest{}

	err = json.Unmarshal(data, &varPowerPanelCoordinateRequest)

	if err != nil {
		return err
	}

	*o = PowerPanelCoordinateRequest(varPowerPanelCoordinateRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "x")
		delete(additionalProperties, "y")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePowerPanelCoordinateRequest struct {
	value *PowerPanelCoordinateRequest
	isSet bool
}

func (v NullablePowerPanelCoordinateRequest) Get() *PowerPanelCoordinateRequest {
	return v.value
}

func (v *NullablePowerPanelCoordinateRequest) Set(val *PowerPanelCoordinateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePowerPanelCoordinateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePowerPanelCoordinateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePowerPanelCoordinateRequest(val *PowerPanelCoordinateRequest) *NullablePowerPanelCoordinateRequest {
	return &NullablePowerPanelCoordinateRequest{value: val, isSet: true}
}

func (v NullablePowerPanelCoordinateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePowerPanelCoordinateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
