/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.5.2-Docker-4.0.0 (4.5)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// checks if the PaginatedPowerPanelCoordinateList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedPowerPanelCoordinateList{}

// PaginatedPowerPanelCoordinateList struct for PaginatedPowerPanelCoordinateList
type PaginatedPowerPanelCoordinateList struct {
	Count                int32                  `json:"count"`
	Next                 NullableString         `json:"next,omitempty"`
	Previous             NullableString         `json:"previous,omitempty"`
	Results              []PowerPanelCoordinate `json:"results"`
	AdditionalProperties map[string]interface{}
}

type _PaginatedPowerPanelCoordinateList PaginatedPowerPanelCoordinateList

// NewPaginatedPowerPanelCoordinateList instantiates a new PaginatedPowerPanelCoordinateList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedPowerPanelCoordinateList(count int32, results []PowerPanelCoordinate) *PaginatedPowerPanelCoordinateList {
	this := PaginatedPowerPanelCoordinateList{}
	this.Count = count
	this.Results = results
	return &this
}

// NewPaginatedPowerPanelCoordinateListWithDefaults instantiates a new PaginatedPowerPanelCoordinateList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedPowerPanelCoordinateListWithDefaults() *PaginatedPowerPanelCoordinateList {
	this := PaginatedPowerPanelCoordinateList{}
	return &this
}

// GetCount returns the Count field value
func (o *PaginatedPowerPanelCoordinateList) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *PaginatedPowerPanelCoordinateList) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *PaginatedPowerPanelCoordinateList) SetCount(v int32) {
	o.Count = v
}

// GetNext returns the Next field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PaginatedPowerPanelCoordinateList) GetNext() string {
	if o == nil || IsNil(o.Next.Get()) {
		var ret string
		return ret
	}
	return *o.Next.Get()
}

// GetNextOk returns a tuple with the Next field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaginatedPowerPanelCoordinateList) GetNextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Next.Get(), o.Next.IsSet()
}

// HasNext returns a boolean if a field has been set.
func (o *PaginatedPowerPanelCoordinateList) HasNext() bool {
	if o != nil && o.Next.IsSet() {
		return true
	}

	return false
}

// SetNext gets a reference to the given NullableString and assigns it to the Next field.
func (o *PaginatedPowerPanelCoordinateList) SetNext(v string) {
	o.Next.Set(&v)
}

// SetNextNil sets the value for Next to be an explicit nil
func (o *PaginatedPowerPanelCoordinateList) SetNextNil() {
	o.Next.Set(nil)
}

// UnsetNext ensures that no value is present for Next, not even an explicit nil
func (o *PaginatedPowerPanelCoordinateList) UnsetNext() {
	o.Next.Unset()
}

// GetPrevious returns the Previous field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PaginatedPowerPanelCoordinateList) GetPrevious() string {
	if o == nil || IsNil(o.Previous.Get()) {
		var ret string
		return ret
	}
	return *o.Previous.Get()
}

// GetPreviousOk returns a tuple with the Previous field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaginatedPowerPanelCoordinateList) GetPreviousOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Previous.Get(), o.Previous.IsSet()
}

// HasPrevious returns a boolean if a field has been set.
func (o *PaginatedPowerPanelCoordinateList) HasPrevious() bool {
	if o != nil && o.Previous.IsSet() {
		return true
	}

	return false
}

// SetPrevious gets a reference to the given NullableString and assigns it to the Previous field.
func (o *PaginatedPowerPanelCoordinateList) SetPrevious(v string) {
	o.Previous.Set(&v)
}

// SetPreviousNil sets the value for Previous to be an explicit nil
func (o *PaginatedPowerPanelCoordinateList) SetPreviousNil() {
	o.Previous.Set(nil)
}

// UnsetPrevious ensures that no value is present for Previous, not even an explicit nil
func (o *PaginatedPowerPanelCoordinateList) UnsetPrevious() {
	o.Previous.Unset()
}

// GetResults returns the Results field value
func (o *PaginatedPowerPanelCoordinateList) GetResults() []PowerPanelCoordinate {
	if o == nil {
		var ret []PowerPanelCoordinate
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *PaginatedPowerPanelCoordinateList) GetResultsOk() ([]PowerPanelCoordinate, bool) {
	if o == nil {
		return nil, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *PaginatedPowerPanelCoordinateList) SetResults(v []PowerPanelCoordinate) {
	o.Results = v
}

func (o PaginatedPowerPanelCoordinateList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedPowerPanelCoordinateList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["count"] = o.Count
	if o.Next.IsSet() {
		toSerialize["next"] = o.Next.Get()
	}
	if o.Previous.IsSet() {
		toSerialize["previous"] = o.Previous.Get()
	}
	toSerialize["results"] = o.Results

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PaginatedPowerPanelCoordinateList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"count",
		"results",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	varPaginatedPowerPanelCoordinateList := _PaginatedPowerPanelCoordinateList{}

	err = json.Unmarshal(data, &varPaginatedPowerPanelCoordinateList)

	if err != nil {
		return err
	}

	*o = PaginatedPowerPanelCoordinateList(varPaginatedPowerPanelCoordinateList)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "count")
		delete(additionalProperties, "next")
		delete(additionalProperties, "previous")
		delete(additionalProperties, "results")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePaginatedPowerPanelCoordinateList struct {
	value *PaginatedPowerPanelCoordinateList
	isSet bool
}

func (v NullablePaginatedPowerPanelCoordinateList) Get() *PaginatedPowerPanelCoordinateList {
	return v.value
}

func (v *NullablePaginatedPowerPanelCoordinateList) Set(val *PaginatedPowerPanelCoordinateList) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedPowerPanelCoordinateList) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedPowerPanelCoordinateList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedPowerPanelCoordinateList(val *PaginatedPowerPanelCoordinateList) *NullablePaginatedPowerPanelCoordinateList {
	return &NullablePaginatedPowerPanelCoordinateList{value: val, isSet: true}
}

func (v NullablePaginatedPowerPanelCoordinateList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedPowerPanelCoordinateList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
