/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.5.2-Docker-4.0.0 (4.5)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// checks if the PrometheusService type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PrometheusService{}

// PrometheusService Serialize a service to Prometheus target representation
type PrometheusService struct {
	Targets              string `json:"targets"`
	Labels               string `json:"labels"`
	AdditionalProperties map[string]interface{}
}

type _PrometheusService PrometheusService

// NewPrometheusService instantiates a new PrometheusService object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrometheusService(targets string, labels string) *PrometheusService {
	this := PrometheusService{}
	this.Targets = targets
	this.Labels = labels
	return &this
}

// NewPrometheusServiceWithDefaults instantiates a new PrometheusService object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrometheusServiceWithDefaults() *PrometheusService {
	this := PrometheusService{}
	return &this
}

// GetTargets returns the Targets field value
func (o *PrometheusService) GetTargets() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Targets
}

// GetTargetsOk returns a tuple with the Targets field value
// and a boolean to check if the value has been set.
func (o *PrometheusService) GetTargetsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Targets, true
}

// SetTargets sets field value
func (o *PrometheusService) SetTargets(v string) {
	o.Targets = v
}

// GetLabels returns the Labels field value
func (o *PrometheusService) GetLabels() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value
// and a boolean to check if the value has been set.
func (o *PrometheusService) GetLabelsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Labels, true
}

// SetLabels sets field value
func (o *PrometheusService) SetLabels(v string) {
	o.Labels = v
}

func (o PrometheusService) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PrometheusService) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["targets"] = o.Targets
	toSerialize["labels"] = o.Labels

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PrometheusService) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"targets",
		"labels",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	varPrometheusService := _PrometheusService{}

	err = json.Unmarshal(data, &varPrometheusService)

	if err != nil {
		return err
	}

	*o = PrometheusService(varPrometheusService)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "targets")
		delete(additionalProperties, "labels")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePrometheusService struct {
	value *PrometheusService
	isSet bool
}

func (v NullablePrometheusService) Get() *PrometheusService {
	return v.value
}

func (v *NullablePrometheusService) Set(val *PrometheusService) {
	v.value = val
	v.isSet = true
}

func (v NullablePrometheusService) IsSet() bool {
	return v.isSet
}

func (v *NullablePrometheusService) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrometheusService(val *PrometheusService) *NullablePrometheusService {
	return &NullablePrometheusService{value: val, isSet: true}
}

func (v NullablePrometheusService) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrometheusService) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
